# Makefile相关公用变量，gcc、as，etcs

# compliers
AS		:= as
LD		:= ld
CC		:= gcc
CXX		:= g++
MAKE		:= make
QEMU		:= qemu-system-i386


# flags
CPPFLAGS	:= -I./include -I../include
#ASFLAGS 	:= $(CPPFLAGS)
LDFLAGS		:= -m elf_i386 -s
CXXFLAGS 	:= -pipe -Wall -Wextra -ffreestanding $(CPPFLAGS) -m32